### ISSUE TITLE
Add `clear-slave-state-from-s3` as an extra hx-deploy-tool command

### ISSUE THREAD

**Issue by jsuresh** [helix-collective/hx-deploy-tool#17]
Or should it be a command of 'proxy-status' (eg. `--refresh-slave-state`)

**Comment by jsuresh** [comment]
Not as important compared to actually making the output nicer.

**Comment by ashvds** [comment]
@jsuresh , @timbod7 believe this is fixed by #69

**Comment by timbod7** [comment]
Yep fixed by #69
