### ISSUE TITLE
Add Various 'Cookbook/Blog' style docs

### ISSUE THREAD

**Issue by jsuresh** [helix-collective/hx-deploy-tool#20]
Thoughts
  * How to have multiple machines run different bits of code
  * Basic setup tutorial
  * Doc on how it all works in auto-scaling mode

**Comment by timbod7** [comment]
Seems like we should use github pages for this this, so that there is a proper website?

**Comment by ashvds** [comment]
@jsuresh @timbod7 
https://help.github.com/en/articles/about-wikis seems like a suitable feature?
also useful for a lot of the doco that I'm ... highlighting is needed.
then apart from the README, the wiki can be used for end user doco, and the repo doco can be focused on contributors.

**Comment by ashvds** [comment]
if you enable it, I will start committing to it  :-)

**Comment by ashvds** [comment]
fixed by #60
