### ISSUE TITLE
Remove terminated slaves from --show-slave status

### ISSUE THREAD

**Issue by fraser-canva** [helix-collective/hx-deploy-tool#27]
I think this is related to #17 but it would be great if the terminated instances were cleared every time `--show-slaves` command is called.

**Comment by jsuresh** [comment]
@fraser-canva - great call actually once we do #5 - this can be a filter (don't show slaves that haven't been updated in 5 mintues for example) - we can assume these are all terminated slaves.

**Comment by ashvds** [comment]
@timbod7 I believe you've fixed this?
In part:
https://github.com/helix-collective/hx-deploy-tool/blob/d41998e928b497dc06513a6cf48dee1a08e28a74/src/Main.hs#L57

Clears statuses more than 5min old.

and

https://github.com/helix-collective/hx-deploy-tool/blob/d41998e928b497dc06513a6cf48dee1a08e28a74/src/Main.hs#L50

now shows slave errors if state is out of sync, and state includes last updated:

https://github.com/helix-collective/hx-deploy-tool/blob/d41998e928b497dc06513a6cf48dee1a08e28a74/src/Commands/ProxyMode.hs#L67

**Comment by timbod7** [comment]
Whilst it hasnt been directly implemented, I made a conscious decision to not filter the slave list, as that will encourage it to grow indefinitely. Rather, we show all the slaves and give the use a command to cleanup the list.

**Comment by ashvds** [comment]
@timbod7 That tidbit would be a useful addition to the 'motivation' section in the documentation
