### ISSUE TITLE
Tool doesn't run if a log file does not exist

### ISSUE THREAD

**Issue by ashvds** [helix-collective/hx-deploy-tool#36]
If the logfile/location in the adl file does not exist, program exits with an error.
Recommend modifying the following to include an if exists else create

https://github.com/helix-collective/hx-deploy-tool/blob/74b075b29a6055d0d349e2fbe2903f6a42e242e2/src/Log.hs#L59

**Comment by ashvds** [comment]
@timbod7 would this be the best  place to add the check?

**Comment by timbod7** [comment]
The code as written should create the log file if it doesn't exist. But (like most unix command line programs), it won't create the parent directory if it's not present.

Are you suggesting that it should create whatever directories are required? An issue with this approach is that often you will want to control owner and permissions for the created directory. Hence it's often easier to create and permission the necessary dir before hx-deploy-tool is run.

**Comment by ashvds** [comment]
Fair, I can add that to the doco then?
