### ISSUE TITLE
S3 buckets listed in config that do not exist result in 'access denied' error

### ISSUE THREAD

**Issue by ashvds** [helix-collective/hx-deploy-tool#43]
If the config.json references a bucket that doesn't exist, the resulting error is non-specific access denied:

> 2019-07-31T05:01:41 [ServiceError] {
>   service    = S3
>   status     = 403 Forbidden
>   code       = AccessDenied
>   message    = Just Access Denied
>   request-id = Just xxxxxx
> }
> 2019-07-31T05:01:41 Exception: ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, _serviceHeaders = [("x-amz-bucket-region","us-east-1"),("x-amz-request-id","xxxxxx"),("x-amz-id-2","xxxxx="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Wed, 31 Jul 2019 05:01:41 GMT"),("Server","AmazonS3")], _serviceCode = ErrorCode "AccessDenied", _serviceMessage = Just (ErrorMessage "Access Denied"), _serviceRequestId = Just (RequestId "xxxxx")

Assuming this is run with the correct credentials inside an AWS account, 'bucket does not exist' via an `s3 ls` may be a more reasonable error.
If the credentials are invalid, `s3 ls` will result in a similar access denied error that can be surfaced.

**Comment by timbod7** [comment]
Perhaps this could be fixed by checking for the bucket presence before attempting to access it.

**Comment by ashvds** [comment]
@timbod7 I can no longer reproduce this issue. Happy for me to close?

**Comment by timbod7** [comment]
Done.
