### ISSUE TITLE
Rename hx_deploy_tool.json

### ISSUE THREAD

**Issue by ashvds** [helix-collective/hx-deploy-tool#47]
the naming convention for the file is not effective in communicating its function.
I would name it `deploy_config.json`
this would infer possibly renaming `release.json` to `release_config.json`

**Comment by timbod7** [comment]
Unsure about this. It's a pretty common convention for a binary    `.../bin/sometool` to have it's config file as `.../etc/sometool.conf` or `.../etc/sometool.json`.

**Comment by jsuresh** [comment]
Real question @timbod7, what should we rename hx-deploy-tool to? soc? doc? 

I quite like soc as the right number of characters for a command line tool, although it's supremely on-googleable. 

What about hxdt (helix deploy tool), or hxdm (Helix deploy manager).

Another idea is to call it son-of-camus or camus2, but make the command line soc or c2?

**Comment by ashvds** [comment]
@jsuresh my vote is for hxdm , says where it comes from and what it does!

**Comment by timbod7** [comment]
We decided camus2, and the file has been renamed accordingly.
