### ISSUE TITLE
Tool expects a .zip

### ISSUE THREAD

**Issue by ashvds** [helix-collective/hx-deploy-tool#48]
using a tar or tar.gz file to pack your release results in an error.

Can be remediated by specifying release archive type in doco.
what should be in a release archive is also not detailed, but that may be mentioned in another issue.

**Comment by timbod7** [comment]
I think this is a documentation issue. Only zip is supported - I don't see a strong case to support other formats.

**Comment by ashvds** [comment]
#60 specifies a .zip now
