### ISSUE TITLE
Tool relies on an existing nginx container running on the target server

### ISSUE THREAD

**Issue by ashvds** [helix-collective/hx-deploy-tool#50]
This either needs to be mentioned in the doco, and specified in detail what the requirements are for the tool to be able to configure it.

OR
The config file/release file, if specifying a proxy, should allow you to pull a specified nginx container to run as sidecar.

**Comment by ashvds** [comment]
This issue makes hx_terraform somewhat of a dependency.

**Comment by timbod7** [comment]
I'm not sure what you mean here. `hx- deploy-tool` starts and manages an nginx proxy in the `frontend_proxy` container. But it doesn't require one to be existing on the machine?

**Comment by ashvds** [comment]
So confusion do to differences between local and remote state tracking with proxy.
Should add doco to clarify how proxy is used, and when. 
i.e. pulls and runs default nginx container only when required, for example when you connect a release to an endpoint.
