### ISSUE TITLE
document the differences in config and requirements for running with proxy in local state vs remote state

### ISSUE THREAD

**Issue by ashvds** [helix-collective/hx-deploy-tool#51]
document the differences in config and requirements for running with proxy in local state vs remote state
such as removing "remoteStateS3": from the config

**Comment by jsuresh** [comment]
@ashvds - should we write cookbook style tutorials for setting up hx-deploy-tool (this would cover this use case, and provide a bit of a flavour for #52

**Comment by ashvds** [comment]
@jsuresh happy to start a wiki 😁

**Comment by jsuresh** [comment]
SGTM - or should we leverage github pages? I think we need a doc that steps one through getting up and running with hx-deploy-tool from scratch? I'll make an issue for this.
